# Generated by Django 2.2.6 on 2019-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juceer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuceerSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_familiarity', models.FloatField()),
                ('artist_hotttnesss', models.FloatField()),
                ('artist_id', models.CharField(max_length=100)),
                ('artist_latitude', models.FloatField()),
                ('artist_location', models.IntegerField()),
                ('artist_longitude', models.FloatField()),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_similar', models.FloatField()),
                ('artist_terms', models.CharField(max_length=100)),
                ('artist_terms_freq', models.FloatField()),
                ('release_id', models.IntegerField()),
                ('release_name', models.IntegerField()),
                ('song_artist_mbtags', models.FloatField()),
                ('song_artist_mbtags_count', models.FloatField()),
                ('song_bars_confidence', models.FloatField()),
                ('song_bars_start', models.FloatField()),
                ('song_beats_confidence', models.FloatField()),
                ('song_beats_start', models.FloatField()),
                ('song_duration', models.FloatField()),
                ('song_end_of_fade_in', models.FloatField()),
                ('song_hotttnesss', models.FloatField()),
                ('song_id', models.SlugField(unique=True)),
                ('song_key', models.FloatField()),
                ('song_key_confidence', models.FloatField()),
                ('song_loudness', models.FloatField()),
                ('song_mode', models.IntegerField()),
                ('song_mode_confidence', models.FloatField()),
                ('song_start_of_fade_out', models.FloatField()),
                ('song_tatums_confidence', models.FloatField()),
                ('song_tatums_start', models.FloatField()),
                ('song_tempo', models.FloatField()),
                ('song_time_signature', models.FloatField()),
                ('song_time_signature_confidence', models.FloatField(max_length=4)),
                ('song_title', models.IntegerField()),
                ('song_year', models.IntegerField()),
            ],
        ),
    ]
