# Generated by Django 2.2.6 on 2019-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juceer', '0004_delete_juceersong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juceerpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='juceerpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='juceerpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='juceerpost',
            name='user',
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='artist_hotttnesss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='artist_id',
            field=models.CharField(default='KnZGS', max_length=100),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='artist_name',
            field=models.CharField(default='H9I49', max_length=100),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='artist_terms',
            field=models.CharField(default='sXzZa', max_length=100),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='release_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='song_hotttnesss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='song_id',
            field=models.SlugField(default='mEhEA', unique=True),
        ),
        migrations.AddField(
            model_name='juceerpost',
            name='song_year',
            field=models.IntegerField(default=0),
        ),
    ]
