# Generated by Django 2.2.6 on 2019-10-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juceer', '0005_auto_20191014_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juceerpost',
            name='artist_id',
            field=models.CharField(default='HuzBk', max_length=100),
        ),
        migrations.AlterField(
            model_name='juceerpost',
            name='artist_name',
            field=models.CharField(default='1Dy1P', max_length=100),
        ),
        migrations.AlterField(
            model_name='juceerpost',
            name='artist_terms',
            field=models.CharField(default='4wJt4', max_length=100),
        ),
        migrations.AlterField(
            model_name='juceerpost',
            name='song_id',
            field=models.SlugField(default='3qCzE', unique=True),
        ),
    ]
