# Generated by Django 2.2.6 on 2019-10-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juceer', '0002_juceersong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juceerpost',
            name='slug',
            field=models.SlugField(),
        ),
    ]
