# Generated by Django 2.2.6 on 2019-10-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juceer', '0003_auto_20191010_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuceerSong',
        ),
    ]
