# Generated by Django 2.2.6 on 2019-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juceer', '0005_auto_20191010_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juceerpost',
            name='artist_id',
            field=models.CharField(default='pQJBO', max_length=100),
        ),
        migrations.AlterField(
            model_name='juceerpost',
            name='artist_name',
            field=models.CharField(default='L1wOs', max_length=100),
        ),
        migrations.AlterField(
            model_name='juceerpost',
            name='artist_terms',
            field=models.CharField(default='aevps', max_length=100),
        ),
        migrations.AlterField(
            model_name='juceerpost',
            name='song_id',
            field=models.SlugField(default='J3STE', unique=True),
        ),
    ]
